---
title: "Network Analytics - Group Assignment 2"
author: "Rollandin Alessandro, Titze Konstantin, Haussmann Maximilian, Ciorciolini Francesco, Borella Riccardo"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(data.table)
library(ggplot2)
library(igraph)

dt.movie.actor <- fread("20200120-imdb_movie_actor.csv")
dt.movie.actor[, n_movies := .N, by = actor]
dt.movie.actor[, n_actors := .N, by = list(movie, year)]
dt.movie.actor <- dt.movie.actor[!(actor == "")]
save(dt.movie.actor, file = "imdb_movie_actor.RData")

load("imdb_movie_actor.RData")
```

## Part 1: `data.table`
### Question 1
```{r}
num_movies <- dt.movie.actor[, uniqueN(movie)]
print(paste("Number of unique movies:", num_movies))
```

### Question 2
```{r}
actors_fight_club <- dt.movie.actor[movie == "Fight Club (1999)", unique(actor)]
print(paste("Actors in Fight Club (1999):", paste(actors_fight_club, collapse = ", ")))

actors_se7en <- dt.movie.actor[movie == "Se7en (1995)", unique(actor)]
print(paste("Actors in Se7en (1995):", paste(actors_se7en, collapse = ", ")))
```

### Question 3
```{r}
actor_both_movies <- intersect(actors_fight_club, actors_se7en)
print(paste("Actor(s) in both movies:", paste(actor_both_movies, collapse = ", ")))
```

### Question 4
```{r}
movie_brad_pitt_george_clooney <- dt.movie.actor[actor %in% c("Brad Pitt (b.1963)", "George Clooney (b.1961)"), unique(movie)]
print(paste("Movie(s) with Brad Pitt and George Clooney:", paste(movie_brad_pitt_george_clooney, collapse = ", ")))
```

### Question 5
```{r}
num_movies_per_year <- dt.movie.actor[, .(n_movies = uniqueN(movie)), by = year][order(year)][, csum_n_movies := cumsum(n_movies)]
print("Number of movies per year:")
print(num_movies_per_year)
```

### Question 6
Add what they have in common
```{r}
top_actor_all <- dt.movie.actor[, .(n = .N), by = actor][order(-n)][1]
print(paste("Top actor overall:", top_actor_all$actor))

top_year_actor <- dt.movie.actor[year >= 2000, .(n = .N), by = .(year, actor)][order(-n)][1]
print(paste("Year with the most movies participations by a single actor/actress:", top_year_actor$year))
print(paste("Top actor in", top_year_actor$year, ":", top_year_actor$actor))

#check to see if these actors have starred in the same movie at least once
movies_both_actors <- intersect(
  dt.movie.actor[actor == top_actor_all$actor, unique(movie)],
  dt.movie.actor[actor == top_year_actor$actor, unique(movie)]
)
print(paste("Movie(s) with both top actors:", paste(movies_both_actors, collapse = ", ")))
```

### Question 7
```{r}
dt_decade <- dt.movie.actor[year >= 2010 & year <= 2019]

threshold <- quantile(dt_decade$votes, 0.90, na.rm = TRUE)

dt_popular <- dt_decade[votes >= threshold]

# PART A
top_10_actors <- dt_popular[, .(n_movies = .N), by = actor][order(-n_movies)][1:10]
print("Top 10 actors with the most popular movies (2010-2019):")
print(top_10_actors)

# PART B
top_year_participation <- dt_popular[, .(n_parts = .N), by = .(year, actor)][order(-n_parts)][1]
print("Year and actor with the most participations:")
print(top_year_participation)
```